version: '3.3'

services:
  bot:
    container_name: discord-bot
    build: .
    env_file:
      - .docker.env
    environment:
      MONGO_URI: 'mongodb://database/discord'
      WAIT_HOSTS: database:27017
    depends_on:
      - database

  database:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

volumes:
  mongo:
